### ISSUE TITLE
WARNING: could not import ForwardShare.MatrixOrScaling into MaxwellTime

### ISSUE THREAD

**Issue by dwfmarchant** [JuliaInv/MaxwellTime#11]
It doesn't look like jInv.ForwardShare.MatrixOrScaling exists and it doesn't look like it's being used.  Can we just get rid of:

https://github.com/JuliaInv/MaxwellTime/blob/367a409046c582f9eba5b2645748716730741fca/src/MaxwellTime.jl#L35

and make the warning go away?

**Comment by Pbellive** [comment]
Done: https://github.com/JuliaInv/MaxwellTime/commit/2b7a2234b90885184103872c81b98ae5b25cbe8e. `jInv.ForwardShare.MatrixOrScaling` exists on a branch I have locally but it's not being used right now. Commented out the import rather than deleting it as a note to maybe come back to that in the future.

**Comment by dwfmarchant** [comment]
Thanks Patrick!
